[package]
name = "rust-cnc"
version = "0.1.0"
authors = ["Patrick Kerrigan"]
edition = "2021"

[dependencies]
libc = "*"
bmp = "*"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
